resolver: lts-8.15
packages:
- '.'
- location:
    git: https://github.com/positiondev/larceny.git
    commit: 48dfe03dafff5eb82da3ea270e89f9bfc7291c86
  extra-dep: true
extra-deps:
- logging-3.0.4
- html-entities-1.1.4
